version: '3.8'
services:
    forsrobin_webb:
        build: 
            context: ./
        restart: always
        image: 'registry-fors.aviliax.com/forsrobin_webb'
        ports:
            - '3000:3000'
        # Load en variables from .env file
        env_file:
            - .env
