version: '3.8'
services:
    forsrobin_webb:
        build: 
            context: ./
        restart: always
        image: '767398027625.dkr.ecr.eu-north-1.amazonaws.com/forsrobin-web'
        ports:
            - '3000:3000'
        # Load en variables from .env file
        env_file:
            - .env
